-- =============================================
-- SQL Server Schema Initialization Script
-- Business: E-commerce Order Management
-- Database: [YourDatabaseName]
-- GENERATED BY AGENT - CLAUDE HAIKU 4.5
-- =============================================

-- Drop existing tables if they exist (in reverse dependency order)
IF OBJECT_ID('dbo.OrderItems', 'U') IS NOT NULL DROP TABLE dbo.OrderItems;
IF OBJECT_ID('dbo.Orders', 'U') IS NOT NULL DROP TABLE dbo.Orders;
IF OBJECT_ID('dbo.Products', 'U') IS NOT NULL DROP TABLE dbo.Products;
IF OBJECT_ID('dbo.Users', 'U') IS NOT NULL DROP TABLE dbo.Users;

-- =============================================
-- Table: Users
-- =============================================
CREATE TABLE dbo.Users (
    UserID INT PRIMARY KEY IDENTITY(1, 1),
    Email VARCHAR(100) UNIQUE NOT NULL,
    FullName NVARCHAR(50),
    CreatedAt DATETIME DEFAULT GETDATE()
);

-- =============================================
-- Table: Products
-- =============================================
CREATE TABLE dbo.Products (
    ProductID INT PRIMARY KEY IDENTITY(1, 1),
    ProductName NVARCHAR(100) NOT NULL,
    UnitPrice DECIMAL(10, 2) NOT NULL,
    StockQuantity INT NOT NULL DEFAULT 0
        CONSTRAINT CK_StockQuantity_NonNegative CHECK (StockQuantity >= 0)
);

-- Create index on ProductName for faster lookups
CREATE INDEX IX_Products_ProductName ON dbo.Products(ProductName);

-- =============================================
-- Table: Orders
-- =============================================
CREATE TABLE dbo.Orders (
    OrderID INT PRIMARY KEY IDENTITY(1, 1),
    UserID INT NOT NULL
        CONSTRAINT FK_Orders_Users FOREIGN KEY REFERENCES dbo.Users(UserID),
    OrderDate DATETIME NOT NULL DEFAULT GETDATE(),
    Status NVARCHAR(20) NOT NULL DEFAULT 'Pending'
        CONSTRAINT CK_OrderStatus CHECK (Status IN ('Pending', 'Completed', 'Cancelled')),
    TotalAmount DECIMAL(12, 2) NOT NULL DEFAULT 0
);

-- Create indexes on Orders for common queries
CREATE INDEX IX_Orders_UserID ON dbo.Orders(UserID);
CREATE INDEX IX_Orders_OrderDate ON dbo.Orders(OrderDate);
CREATE INDEX IX_Orders_Status ON dbo.Orders(Status);

-- =============================================
-- Table: OrderItems
-- =============================================
CREATE TABLE dbo.OrderItems (
    OrderID INT NOT NULL
        CONSTRAINT FK_OrderItems_Orders FOREIGN KEY REFERENCES dbo.Orders(OrderID) ON DELETE CASCADE,
    ProductID INT NOT NULL
        CONSTRAINT FK_OrderItems_Products FOREIGN KEY REFERENCES dbo.Products(ProductID),
    Quantity INT NOT NULL
        CONSTRAINT CK_OrderItems_Quantity_Positive CHECK (Quantity > 0),
    UnitPrice DECIMAL(10, 2) NOT NULL,
    CONSTRAINT PK_OrderItems PRIMARY KEY (OrderID, ProductID)
);

-- Create indexes for performance
CREATE INDEX IX_OrderItems_ProductID ON dbo.OrderItems(ProductID);

-- =============================================
-- Sample Data Insertion (Optional)
-- =============================================

-- Insert sample users
INSERT INTO dbo.Users (Email, FullName) VALUES
('alice@example.com', N'Alice Nguyen'),
('bob@example.com', N'Bob Smith'),
('charlie@example.com', N'Charlie Johnson');

-- Insert sample products
INSERT INTO dbo.Products (ProductName, UnitPrice, StockQuantity) VALUES
(N'Laptop Dell XPS 13', 1299.99, 10),
(N'Mouse Logitech MX', 99.99, 50),
(N'Keyboard Mechanical RGB', 199.99, 25),
(N'Monitor LG 27"', 349.99, 8);

-- Insert sample orders
INSERT INTO dbo.Orders (UserID, Status, TotalAmount) VALUES
(1, 'Completed', 1399.98),
(2, 'Pending', 199.99),
(1, 'Cancelled', 0.00);

-- Insert sample order items
INSERT INTO dbo.OrderItems (OrderID, ProductID, Quantity, UnitPrice) VALUES
(1, 1, 1, 1299.99),   -- Alice ordered 1 Laptop
(1, 2, 1, 99.99),     -- + 1 Mouse
(2, 3, 1, 199.99),    -- Bob ordered 1 Keyboard
(3, 4, 2, 349.99);    -- Charlie ordered 2 Monitors (cancelled)

-- =============================================
-- Verification Queries
-- =============================================

-- Check table creation
PRINT '=== Table Structure ===';
EXEC sp_tables @table_owner = 'dbo';

-- Verify data
PRINT '=== Users ===';
SELECT * FROM dbo.Users;

PRINT '=== Products ===';
SELECT * FROM dbo.Products;

PRINT '=== Orders ===';
SELECT * FROM dbo.Orders;

PRINT '=== OrderItems ===';
SELECT * FROM dbo.OrderItems;

PRINT '=== Order Summary (with details) ===';
SELECT 
    o.OrderID,
    u.FullName AS CustomerName,
    o.OrderDate,
    o.Status,
    COUNT(oi.ProductID) AS ItemCount,
    o.TotalAmount
FROM dbo.Orders o
INNER JOIN dbo.Users u ON o.UserID = u.UserID
LEFT JOIN dbo.OrderItems oi ON o.OrderID = oi.OrderID
GROUP BY o.OrderID, u.FullName, o.OrderDate, o.Status, o.TotalAmount
ORDER BY o.OrderID;
